version: '3.8'

services:
  # Viewer Portal
  viewer-portal:
    build:
      context: .
      dockerfile: apps/viewer-portal/Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./apps/viewer-portal:/app
      - ./packages:/packages
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=https://api.streaming-platform.com
      - REACT_APP_AWS_REGION=eu-west-2
      - REACT_APP_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - REACT_APP_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
    depends_on:
      - shared-packages

  # Creator Dashboard
  creator-dashboard:
    build:
      context: .
      dockerfile: apps/creator-dashboard/Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ./apps/creator-dashboard:/app
      - ./packages:/packages
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=https://api.streaming-platform.com
      - REACT_APP_AWS_REGION=eu-west-2
      - REACT_APP_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - REACT_APP_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
    depends_on:
      - shared-packages

  # Admin Portal
  admin-portal:
    build:
      context: .
      dockerfile: apps/admin-portal/Dockerfile.dev
    ports:
      - "3003:3000"
    volumes:
      - ./apps/admin-portal:/app
      - ./packages:/packages
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=https://api.streaming-platform.com
      - REACT_APP_AWS_REGION=eu-west-2
      - REACT_APP_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - REACT_APP_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
    depends_on:
      - shared-packages

  # Support System
  support-system:
    build:
      context: .
      dockerfile: apps/support-system/Dockerfile.dev
    ports:
      - "3004:3000"
    volumes:
      - ./apps/support-system:/app
      - ./packages:/packages
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=https://api.streaming-platform.com
      - REACT_APP_AWS_REGION=eu-west-2
      - REACT_APP_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - REACT_APP_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
    depends_on:
      - shared-packages

  # Analytics Dashboard
  analytics-dashboard:
    build:
      context: .
      dockerfile: apps/analytics-dashboard/Dockerfile.dev
    ports:
      - "3005:3000"
    volumes:
      - ./apps/analytics-dashboard:/app
      - ./packages:/packages
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=https://api.streaming-platform.com
      - REACT_APP_AWS_REGION=eu-west-2
      - REACT_APP_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - REACT_APP_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
    depends_on:
      - shared-packages

  # Developer Console
  developer-console:
    build:
      context: .
      dockerfile: apps/developer-console/Dockerfile.dev
    ports:
      - "3006:3000"
    volumes:
      - ./apps/developer-console:/app
      - ./packages:/packages
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=https://api.streaming-platform.com
      - REACT_APP_AWS_REGION=eu-west-2
      - REACT_APP_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - REACT_APP_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
    depends_on:
      - shared-packages

  # Shared packages builder
  shared-packages:
    build:
      context: .
      dockerfile: Dockerfile.packages
    volumes:
      - ./packages:/packages
    command: npm run build

networks:
  default:
    name: streaming-platform-dev